---
title: "Information on Site Class Identifier"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
```

# Instructions
This function allows the user to upload station information and assigns natural StreamCat factors. Some metrics are adjusted based on site-specific StreamCat estimates. **See Background tab for metric calculations.** Note, the user must associate sites with NHDPlus V2 COMIDs using GIS (outside of the app). There are over 75,000 unique COMIDs in WY; however, there are approximately 50 COMIDs with some missing StreamCat data. Regardless, any missing StreamCat data will cause index scores to be incorrectly calculated. **Site elevation (ft)** is also a metric adjustment factor, but must be provided by the user. **Finally, the downloaded metric adjustment factor data will need to be merged with taxonomic data (outside of the app) to properly calculate the index.**

Follow the steps to the left to upload a site and COMID table. For more information on the derivation of these metric adjustment factors, please read the [Wyoming Diatom IBI report](https://github.com/Blocktt/ShinyAppDocuments/tree/main/WDEQtools/Reports). Feel free to download an [Example file](https://github.com/Blocktt/ShinyAppDocuments/tree/main/WDEQtools/Example_Files) to understand how the function works.
