---
title: "Assign Index Class, About"
date: "2023-07-28"
output: html_fragment
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE
                      , results = 'asis'
                      , warning = FALSE
                      , message = FALSE)
```

# Purpose

Create a file with the predictor variablesfor the KS MMI calculation.
After you merge this file with the Taxa Translator/Add Attributes
output, your input file will be ready to run through the MMI calculator.

Your input file must have the following four fields:

-   Unique identifier (e.g., SampleID) that can be joined with the Taxa
    Translator/Add Attributes output

-   Latitude (decimal degrees)

-   Longitude (decimal degrees)

-   CFS (modeled median flow based on Perry et al. 2004)

The EPSG field (datum for coordinates) can be left blank (it will be
populated with the value 4269 (NAD83, North America)
- <https://epsg.io/4269>).

The underlying code in the Shiny app will use the lat/longs to match the
sites with NHDPlusV2 catchments and COMIDs (unique identifiers); the
<a href="https:://raw.githubusercontent.com/Blocktt/KDHEtools/main/inst/shiny-examples/KDHEtools/data/KS_StreamCat_PredictorTable_BenB_20230721.xlsx" target="_blank">predictor
variables</a> are then joined to the input file via the COMID.

For more information about how the CFS field was derived for MMI
development, contact Liz Smith (Elizabeth.Smith@ks.gov).

Want to try it? You can download a test file
<a href="https:://raw.githubusercontent.com/Blocktt/ShinyAppDocuments/main/KDHEtools/Example_Files/Test1_FileBuilder_Predictor.csv" target="_blank">here</a>.

# Disclaimers

The StreamCat R tools that are used to match your sites with the
NHDPlusV2 stream segment identifiers (COMIDs) do not have QC measures.
At a minimum, we recommend the following check:

-   Include waterbody name in your input file and check against
    'gnis_name' in the output file (which is derived from the NHDPlusV2
    dataset); if they don't match, investigate.

Depending on the size of your input file, this function may several
minutes to run (e.g., 5-10 minutes). Be patient. There is a lot going on
behind the scenes.
