---
title: "Merge Files, About"
date: "2023-02-03"
output: html_fragment
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE
                      , results = 'asis'
                      , warning = FALSE
                      , message = FALSE)
```

# Purpose

Finish creating your input file by merging the outputs from the Taxa
Translator/Add Attributes and Generate Predictors tabs.

Upload the files (the order shouldn't matter) and select a single common
identifier from each file to perform the merge (e.g., SampleID). The
common identifier doesn't need to be named the same thing in both files.
Just click on the drop-down menus and the list of fields in your input
files will appear. Select the correct identifiers from each file.

In the output file, column names that overlap across the two files will
have the suffix '.x' or '.y' for files 1 and 2 , respectively.

You will have the option of viewing both input files before merging.

You can only merge two files at a time. If you want to join more, do one
pair first, then join that file with the next file, and so on.

![Merge file conceptual
layout.](images%5CFileBuilder_MergeFiles_About_Fig1.jpg)
