---
title: "Instructions and Background Information"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
```

# Calculate MMI Instructions

KDHEtools was developed to calculate macroinvertebrate metrics and a Multi-Metric Index (MMI) for wadeable streams in Kansas. Detailed documentation of the Kansas Macroinvertebrate MMI development can be found [here](https://github.com/Blocktt/ShinyAppDocuments/tree/main/KDHEtools/Reports). Users can run any data through the Index calculator and get a result. However, if samples do not meet the criteria listed below, results should be interpreted with caution. Links to an example input file and a document containing more detailed information on preparing the input file are also provided.

The user should follow the onscreen instructions as follows:

1.  Load file
    -   **Default settings work well**. If the user is unsure of how to format the data, simply store as a .csv and use the default load settings.
    -   An example input file can be downloaded from Github [EXAMPLE LINK](https://github.com/Blocktt/ShinyAppDocuments/tree/main/KDHEtools/Example_Files)
    -   Choose Separator. The separator indicates how the data is stored. Comma indicates the input file is a comma-separated file (.csv). Tab indicates the input file is a tab-separated file (.txt or .tsv). Finally, Semicolon indicates the input file is a semicolon-separated file which is uncommon in the United States but common in western European countries. Be certain that the designated separator is not used in any of the text fields.
    -   Choose Quote. The quote indicates how the data is stored. Double quote is the most common.
    -   Choose file to upload. Hit the browse button and search for the input file.
    -   Once uploaded, make sure data look correct in the viewer. If the incorrect Separator or Quote is chosen, the user may receive an error or the data may look incorrect in the viewer.
2.  Calculate Index
    -   Click the 'Calculate Metric Values and Scores' button.
    -   A progress bar will appear in the bottom, right corner of the screen. Results cannot be downloaded (step 3) until the progress bar is completed and disappears.
3.  Download results
    -   Select the button to download a zip file with inputs and results.
    -   Check 'results_log.txt' for any warnings or messages. Note, some warnings are automatically generated by R. Feel free to reach out to Ben Block (Ben.Block\@tetratech.com) for any questions related to warnings.
