---
title: "Background Information"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
always_allow_html: true
output:
  html_fragment:
    toc: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE, message = FALSE)
```

## Background

This website calculates Multi-Metric Index (MMI) scores for benthic
macroinvertebrate samples collected from wadeable streams in Kansas. A
report detailing the development of the Kansas Macroinvertebrate MMI can
be found
<a href="https://raw.githubusercontent.com/Blocktt/ShinyAppDocuments/main/KDHEtools/Reports/KS_MMI_FinalReport.zip" target="_blank">here</a>.

This is a Shiny app website. There is underlying R code that does the
MMI calculation. The user clicks buttons to upload .csv input files and
download results. Those who prefer to work directly with R can download
the R code from Ben Block's GitHub repository
<a href="https://github.com/Blocktt/KDHEtools/" target="_blank">here</a>.

Want to try running the calculator but don't have input files? Click
<a href="https://github.com/Blocktt/ShinyAppDocuments/tree/main/KDHEtools/Example_Files/" target="_blank">here</a>
to download test files.

## Funding

Development of KDHEtools and the underlying MMI was funded by the Kansas
Department of Health and Environment (KDHE). For more information,
please contact Tony Stahl (Anthony.Stahl@ks.gov).

## Intended application

The KS MMI improves the diagnostic ability of KDHE and other
practitioners to identify degradation in biological integrity and water
quality. It is intended to be applied to samples that meet the following
criteria:

-   Geographic area: Kansas

-   Stream type: freshwater, wadeable

-   Subsample size: \>= 200-count samples are recommended for best
    performance; results for samples with \<100 individuals should be
    interpreted with caution

-   Taxonomic resolution: genus or species-level as allowed by available
    keys, specimen condition, and specimen maturity

-   Collection gear: 500-µm mesh D-frame net and fine point forceps •
    Collection period: April 15--October 15

-   Collection method: KDHE Stream Probabilistic
    (<a href="https://www.kdhe.ks.gov/1230/Stream-Probabilistic" target="_blank">SP</a>) program or
    Stream Biological
    (<a href="https://www.kdhe.ks.gov/1233/Stream-Biological-Monitoring-Program" target="_blank">SB</a>)
    Monitoring Program protocols. Organisms are composited from multiple
    habitats. Field staff try to maximize the diversity of organisms
    being captured, targeting macrohabitats (riffles, leafpacks,
    undercut banks and rootmats, fine substrate, aquatic vegetation, and
    large woody debris). One or two-person field crews collect organisms
    with 500-µm mesh D-frame nets, using sweeps or kicks, or by hand
    picking organisms off large hard substrates. Organisms are picked in
    the field and identified in the lab.

-   Predictor variables: results for sites with predictor values outside
    the range of values represented in the MMI reference calibration
    dataset should be interpreted with caution. For more information,
    see Table 13 in the MMI report.

For more information on sampling methodologies and application limits,
see the Kansas Macroinvertebrate MMI development report
<a href="https://raw.githubusercontent.com/Blocktt/ShinyAppDocuments/main/KDHEtools/Reports/KS_MMI_FinalReport.zip" target="_blank">here</a>.
